#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

variable "region" {
  type = string
  validation {
    condition     = can(regex("^(us|af|ap|ca|eu|me|sa|cn)\\-(east|west|south|northeast|southeast|central|north|northwest)\\-(1|2|3)$", var.region))
    error_message = "The region must be a proper AWS region."
  }
}

variable "vpc_name" {
  description = "The name used for the VPC and associated resources"
  type        = string
}

variable "num_azs" {
  type        = number
  description = "The number of availability zones to provision"
  default     = 2
}

variable "private_subnet_start" {
  default     = 10
  description = "The starting octet for the private subnet CIDR blocks generated by this module."
  type        = number
}

variable "public_subnet_start" {
  default     = 20
  description = "The starting octet for the public subnet CIDR blocks generated by this module."
  type        = number
}

variable "private_subnet_newbits" {
  default     = 8
  description = "The number of bits to added to the VPC CIDR prefix. For instance, if your VPC CIDR is a /16 and you set this number to 8, the subnets will be /24s."
  type        = number
}

variable "public_subnet_newbits" {
  default     = 8
  description = "The number of bits to added to the VPC CIDR prefix. For instance, if your VPC CIDR is a /16 and you set this number to 8, the subnets will be /24s."
  type        = number
}

variable "public_subnet_auto_ip" {
  type    = bool
  default = false
}

variable "tags" {
  default     = {}
  description = "Additional to apply to the resources. Note that this module sets the tags Name, Type, and Vendor by default. They can be overwritten, but it is not recommended."
  type        = map(string)
  deprecation = "This was an inconsistent name for the variable. Please use \"additional_tags\" instead."
}

variable "additional_tags" {
  default     = {}
  description = "Additional tags to apply to the resources. Note that this module sets the tags Name, Type, and Vendor by default. They can be overwritten, but it is not recommended."
  type        = map(string)
}

variable "vpc_cidr" {
  description = "The CIDR range to be used by the AWS VPC. We recommend using a /16 prefix to automatically generate /24 subnets. If you are using a smaller or larger prefix, refer to the subnet_newbits variable to ensure that the generated subnet ranges are a valid for EKS (minimum /24 is recommended)."
  type        = string
}
